// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHe_mKOIVGS6Anbe6JXswYMItEYbe0rg',
    appId: '1:7613964766:web:96f2f31f9971b0ac9bfd4f',
    messagingSenderId: '7613964766',
    projectId: 'pimoviles-eefc0',
    authDomain: 'pimoviles-eefc0.firebaseapp.com',
    storageBucket: 'pimoviles-eefc0.firebasestorage.app',
    measurementId: 'G-8JM2XD5P7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkXijWRo3UbCCbdwR3pqKSZR6MQ-AV900',
    appId: '1:7613964766:android:10751f7c3d53ddb69bfd4f',
    messagingSenderId: '7613964766',
    projectId: 'pimoviles-eefc0',
    storageBucket: 'pimoviles-eefc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh8n-KuNRoe9sb4-j454GO66g4vPrgUio',
    appId: '1:7613964766:ios:0c9d53fc42e1ec1b9bfd4f',
    messagingSenderId: '7613964766',
    projectId: 'pimoviles-eefc0',
    storageBucket: 'pimoviles-eefc0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh8n-KuNRoe9sb4-j454GO66g4vPrgUio',
    appId: '1:7613964766:ios:0c9d53fc42e1ec1b9bfd4f',
    messagingSenderId: '7613964766',
    projectId: 'pimoviles-eefc0',
    storageBucket: 'pimoviles-eefc0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsHe_mKOIVGS6Anbe6JXswYMItEYbe0rg',
    appId: '1:7613964766:web:a22c3af64cce2dae9bfd4f',
    messagingSenderId: '7613964766',
    projectId: 'pimoviles-eefc0',
    authDomain: 'pimoviles-eefc0.firebaseapp.com',
    storageBucket: 'pimoviles-eefc0.firebasestorage.app',
    measurementId: 'G-9ZPMWNC2ML',
  );
}
